<?php
  include_once("config.php");
  include_once("f_debug.php");
  include_once("f_string.php");
  include_once("f_db.php");
  include_once("f_array.php");
  include_once("f_misc.php");
  include_once("f_form.php");
  include_once("f_html.php");
  include_once("f_date.php");
  include_once("f_registros.php");
